#
#   @copyright  Copyright (C) 2011 Oleg Kertanov <okertanov@gmail.com>
#   @license    BSD
#

mini-os-all:
	$(MAKE) -C extras/mini-os

mini-os-clean:
	$(MAKE) -C extras/mini-os clean

.PHONY: mini-os-all mini-os-clean

