#
#   @copyright  Copyright (C) 2011 Oleg Kertanov <okertanov@gmail.com>
#   @license    BSD
#

all:
	$(MAKE) -C boot $@
	$(MAKE) -C lib $@

clean:
	$(MAKE) -C boot $@
	$(MAKE) -C lib $@

.PHONY: all clean

