##    Copyright (C) 2011 Oleg Kertanov <okertanov@gmail.com>
##    All rights reserved.

include ../Makefile.common

MODULE_NAME := API

SOURCES := VelaOS.cpp
TARGETS := $(BUILD_DIR)/libvelaapi.a

include ../Makefile.targets

