##    Copyright (C) 2011 Oleg Kertanov <okertanov@gmail.com>
##    All rights reserved.

include ../Makefile.common

MODULE_NAME := CORE

SOURCES := Types.cpp String.cpp ABI.cpp Runtime.cpp Language.cpp Log.cpp Platform.cpp \
           Fiber.cpp Task.cpp Concurrent.cpp Memory.cpp Ipc.cpp Interpreter.cpp \
           Error.cpp Debug.cpp
TARGETS := $(BUILD_DIR)/libvelacore.a

include ../Makefile.targets

