##    Copyright (C) 2011 Oleg Kertanov <okertanov@gmail.com>
##    All rights reserved.

include ../../Makefile.common

MODULE_NAME := PAL/Win32

SOURCES := Win32Platform.cpp
TARGETS := $(BUILD_DIR)/libvelapal.a

include ../../Makefile.targets

